//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDentalWitt.NetDentServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NetDentServices.ITestService1")]
    public interface ITestService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITestService1/DoWork", ReplyAction="http://tempuri.org/ITestService1/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITestService1/DoWork", ReplyAction="http://tempuri.org/ITestService1/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITestService1/SetDiagType", ReplyAction="http://tempuri.org/ITestService1/SetDiagTypeResponse")]
        bool SetDiagType(string Chari);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITestService1/SetDiagType", ReplyAction="http://tempuri.org/ITestService1/SetDiagTypeResponse")]
        System.Threading.Tasks.Task<bool> SetDiagTypeAsync(string Chari);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITestService1Channel : CDentalWitt.NetDentServices.ITestService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TestService1Client : System.ServiceModel.ClientBase<CDentalWitt.NetDentServices.ITestService1>, CDentalWitt.NetDentServices.ITestService1 {
        
        public TestService1Client() {
        }
        
        public TestService1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TestService1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TestService1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TestService1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public bool SetDiagType(string Chari) {
            return base.Channel.SetDiagType(Chari);
        }
        
        public System.Threading.Tasks.Task<bool> SetDiagTypeAsync(string Chari) {
            return base.Channel.SetDiagTypeAsync(Chari);
        }
    }
}
