//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_LIB
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiagType
    {
        public DiagType()
        {
            this.Diagpiece = new HashSet<Diagpiece>();
        }
    
        public int Id { get; set; }
        public string Characteristic { get; set; }
    
        public virtual ICollection<Diagpiece> Diagpiece { get; set; }
    }
}
