//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_LIB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diagpiece
    {
        public Diagpiece()
        {
            this.Tooth = new HashSet<Tooth>();
            this.Tooth1 = new HashSet<Tooth>();
            this.Tooth2 = new HashSet<Tooth>();
            this.Tooth3 = new HashSet<Tooth>();
            this.Tooth4 = new HashSet<Tooth>();
            this.Tooth5 = new HashSet<Tooth>();
            this.Tooth6 = new HashSet<Tooth>();
            this.Tooth7 = new HashSet<Tooth>();
            this.Tooth8 = new HashSet<Tooth>();
        }
    
        public int Id { get; set; }
        public string Definition { get; set; }
        public string Type { get; set; }
        public string Ubication { get; set; }
        public string Extention { get; set; }
    
        public virtual DiagType DiagType { get; set; }
        public virtual DiagUbication DiagUbication { get; set; }
        public virtual ExtentionDent ExtentionDent { get; set; }
        public virtual ICollection<Tooth> Tooth { get; set; }
        public virtual ICollection<Tooth> Tooth1 { get; set; }
        public virtual ICollection<Tooth> Tooth2 { get; set; }
        public virtual ICollection<Tooth> Tooth3 { get; set; }
        public virtual ICollection<Tooth> Tooth4 { get; set; }
        public virtual ICollection<Tooth> Tooth5 { get; set; }
        public virtual ICollection<Tooth> Tooth6 { get; set; }
        public virtual ICollection<Tooth> Tooth7 { get; set; }
        public virtual ICollection<Tooth> Tooth8 { get; set; }
    }
}
