//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_LIB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Model1Container : DbContext
    {
        public Model1Container()
            : base("name=Model1Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Diagpiece> DiagpieceSet { get; set; }
        public virtual DbSet<DiagUbication> DiagUbicationSet { get; set; }
        public virtual DbSet<ExtentionDent> ExtentionDentSet { get; set; }
        public virtual DbSet<DiagType> DiagTypeSet { get; set; }
        public virtual DbSet<Tooth> ToothSet { get; set; }
        public virtual DbSet<Patient> PatientSet { get; set; }
        public virtual DbSet<ClinicalHistory> ClinicalHistorySet { get; set; }
    }
}
