//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_LIB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public int Id { get; set; }
        public string DNI { get; set; }
        public string FirstName { get; set; }
        public string SecondName { get; set; }
        public string FamName { get; set; }
        public string LastName { get; set; }
    
        public virtual ClinicalHistory ClinicalHistory { get; set; }
    }
}
