//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_LIB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tooth
    {
        public Tooth()
        {
            this.ClinicalHistory = new HashSet<ClinicalHistory>();
        }
    
        public int Id { get; set; }
        public string Position { get; set; }
        public string OC { get; set; }
        public string VE { get; set; }
        public string LI { get; set; }
        public string ME { get; set; }
        public string DI { get; set; }
        public string CV { get; set; }
        public string CL { get; set; }
        public string ROOT { get; set; }
        public string EXTRA { get; set; }
        public string ClinHist { get; set; }
    
        public virtual Diagpiece Diagpiece { get; set; }
        public virtual Diagpiece Diagpiece1 { get; set; }
        public virtual Diagpiece Diagpiece2 { get; set; }
        public virtual Diagpiece Diagpiece3 { get; set; }
        public virtual Diagpiece Diagpiece4 { get; set; }
        public virtual Diagpiece Diagpiece5 { get; set; }
        public virtual Diagpiece Diagpiece6 { get; set; }
        public virtual Diagpiece Diagpiece7 { get; set; }
        public virtual Diagpiece Diagpiece8 { get; set; }
        public virtual ICollection<ClinicalHistory> ClinicalHistory { get; set; }
    }
}
